#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
public partial class institucionDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void Insertalumnos(alumnos instance);
  partial void Updatealumnos(alumnos instance);
  partial void Deletealumnos(alumnos instance);
  partial void InsertCurss(Curss instance);
  partial void UpdateCurss(Curss instance);
  partial void DeleteCurss(Curss instance);
  #endregion
	
	public institucionDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public institucionDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public institucionDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public institucionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public institucionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<alumnos> alumnos
	{
		get
		{
			return this.GetTable<alumnos>();
		}
	}
	
	public System.Data.Linq.Table<Curss> Curss
	{
		get
		{
			return this.GetTable<Curss>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumnos")]
public partial class alumnos : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _codigo;
	
	private string _nombre;
	
	private string _apellido;
	
	private string _DNI;
	
	private string _direccion;
	
	private string _telefono;
	
	private string _grado;
	
	private string _seccion;
	
	private string _level;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OngradoChanging(string value);
    partial void OngradoChanged();
    partial void OnseccionChanging(string value);
    partial void OnseccionChanged();
    partial void OnlevelChanging(string value);
    partial void OnlevelChanged();
    #endregion
	
	public alumnos()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string codigo
	{
		get
		{
			return this._codigo;
		}
		set
		{
			if ((this._codigo != value))
			{
				this.OncodigoChanging(value);
				this.SendPropertyChanging();
				this._codigo = value;
				this.SendPropertyChanged("codigo");
				this.OncodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50)")]
	public string apellido
	{
		get
		{
			return this._apellido;
		}
		set
		{
			if ((this._apellido != value))
			{
				this.OnapellidoChanging(value);
				this.SendPropertyChanging();
				this._apellido = value;
				this.SendPropertyChanged("apellido");
				this.OnapellidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(50)")]
	public string DNI
	{
		get
		{
			return this._DNI;
		}
		set
		{
			if ((this._DNI != value))
			{
				this.OnDNIChanging(value);
				this.SendPropertyChanging();
				this._DNI = value;
				this.SendPropertyChanged("DNI");
				this.OnDNIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50)")]
	public string direccion
	{
		get
		{
			return this._direccion;
		}
		set
		{
			if ((this._direccion != value))
			{
				this.OndireccionChanging(value);
				this.SendPropertyChanging();
				this._direccion = value;
				this.SendPropertyChanged("direccion");
				this.OndireccionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50)")]
	public string telefono
	{
		get
		{
			return this._telefono;
		}
		set
		{
			if ((this._telefono != value))
			{
				this.OntelefonoChanging(value);
				this.SendPropertyChanging();
				this._telefono = value;
				this.SendPropertyChanged("telefono");
				this.OntelefonoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grado", DbType="VarChar(50)")]
	public string grado
	{
		get
		{
			return this._grado;
		}
		set
		{
			if ((this._grado != value))
			{
				this.OngradoChanging(value);
				this.SendPropertyChanging();
				this._grado = value;
				this.SendPropertyChanged("grado");
				this.OngradoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seccion", DbType="VarChar(50)")]
	public string seccion
	{
		get
		{
			return this._seccion;
		}
		set
		{
			if ((this._seccion != value))
			{
				this.OnseccionChanging(value);
				this.SendPropertyChanging();
				this._seccion = value;
				this.SendPropertyChanged("seccion");
				this.OnseccionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="VarChar(50)")]
	public string level
	{
		get
		{
			return this._level;
		}
		set
		{
			if ((this._level != value))
			{
				this.OnlevelChanging(value);
				this.SendPropertyChanging();
				this._level = value;
				this.SendPropertyChanged("level");
				this.OnlevelChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Curss")]
public partial class Curss : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _CodigoCurso;
	
	private string _NombreCurso;
	
	private string _cod_alumno;
	
	private string _Nota1;
	
	private string _Nota2;
	
	private string _Nota3;
	
	private string _promedio;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoCursoChanging(string value);
    partial void OnCodigoCursoChanged();
    partial void OnNombreCursoChanging(string value);
    partial void OnNombreCursoChanged();
    partial void Oncod_alumnoChanging(string value);
    partial void Oncod_alumnoChanged();
    partial void OnNota1Changing(string value);
    partial void OnNota1Changed();
    partial void OnNota2Changing(string value);
    partial void OnNota2Changed();
    partial void OnNota3Changing(string value);
    partial void OnNota3Changed();
    partial void OnpromedioChanging(string value);
    partial void OnpromedioChanged();
    #endregion
	
	public Curss()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCurso", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string CodigoCurso
	{
		get
		{
			return this._CodigoCurso;
		}
		set
		{
			if ((this._CodigoCurso != value))
			{
				this.OnCodigoCursoChanging(value);
				this.SendPropertyChanging();
				this._CodigoCurso = value;
				this.SendPropertyChanged("CodigoCurso");
				this.OnCodigoCursoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCurso", DbType="VarChar(50)")]
	public string NombreCurso
	{
		get
		{
			return this._NombreCurso;
		}
		set
		{
			if ((this._NombreCurso != value))
			{
				this.OnNombreCursoChanging(value);
				this.SendPropertyChanging();
				this._NombreCurso = value;
				this.SendPropertyChanged("NombreCurso");
				this.OnNombreCursoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_alumno", DbType="VarChar(10)")]
	public string cod_alumno
	{
		get
		{
			return this._cod_alumno;
		}
		set
		{
			if ((this._cod_alumno != value))
			{
				this.Oncod_alumnoChanging(value);
				this.SendPropertyChanging();
				this._cod_alumno = value;
				this.SendPropertyChanged("cod_alumno");
				this.Oncod_alumnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota1", DbType="VarChar(10)")]
	public string Nota1
	{
		get
		{
			return this._Nota1;
		}
		set
		{
			if ((this._Nota1 != value))
			{
				this.OnNota1Changing(value);
				this.SendPropertyChanging();
				this._Nota1 = value;
				this.SendPropertyChanged("Nota1");
				this.OnNota1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota2", DbType="VarChar(10)")]
	public string Nota2
	{
		get
		{
			return this._Nota2;
		}
		set
		{
			if ((this._Nota2 != value))
			{
				this.OnNota2Changing(value);
				this.SendPropertyChanging();
				this._Nota2 = value;
				this.SendPropertyChanged("Nota2");
				this.OnNota2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota3", DbType="VarChar(10)")]
	public string Nota3
	{
		get
		{
			return this._Nota3;
		}
		set
		{
			if ((this._Nota3 != value))
			{
				this.OnNota3Changing(value);
				this.SendPropertyChanging();
				this._Nota3 = value;
				this.SendPropertyChanged("Nota3");
				this.OnNota3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_promedio", DbType="VarChar(10)")]
	public string promedio
	{
		get
		{
			return this._promedio;
		}
		set
		{
			if ((this._promedio != value))
			{
				this.OnpromedioChanging(value);
				this.SendPropertyChanging();
				this._promedio = value;
				this.SendPropertyChanged("promedio");
				this.OnpromedioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
